

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_converter_app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"

volumes:
  media:
