apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: decimator1/django-converter:latest 
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/db  
          name: django-storage
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "your_project.settings"
      volumes:
      - name: django-storage
        persistentVolumeClaim:
          claimName: django-pvc
